version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./src/:/app/src/
      - ./sandbox/settings.py:/app/sandbox/settings.py
    # command: >
    #   sh -c "python manage.py runserver 0.0.0.0:8000"